steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg=API_URL=${_API_URL}
      - --build-arg=VACATION_API_URL=${_VACATION_API_URL}
      - -t=${_IMAGE}
      - .

images:
  - ${_IMAGE}
